spring:
  datasource:
    url: jdbc:dm://172.19.224.131:5236/ZBPT
    driver-class-name: dm.jdbc.driver.DmDriver
    username: ZBPT
    password: ZBPT@dm@2024
    hikari:
      maximum-pool-size: 10
logging:
  level:
    org.springframework.jdbc.core: TRACE
